name: "Bug report"
description: "Create a report to help us improve"
body:
-
    type: "input"
    attributes:
        label: "Root version"
        placeholder: "#.#.#"
    validations:
        required: true
-
    type: "input"
    attributes:
        label: "Laravel version"
        placeholder: "#.#.#"
    validations:
        required: false
-
    type: "input"
    attributes:
        label: "PHP version"
        placeholder: "#.#.#"
    validations:
        required: false
-
    type: "input"
    attributes:
        label: "Database engine & version"
        placeholder: "#.#"
    validations:
        required: false
-
    type: "textarea"
    attributes:
        label: "Description"
    validations:
        required: true
-
    type: "textarea"
    attributes:
        label: "Steps To Reproduce"
        description: "Description example"
        placeholder: "Placeholder example"
    validations:
        required: true
