name: "Bug report"
description: "Create a report to help us improve"
body:
-
    type: "input"
    attributes:
        label: "Root version"
        placeholder: "#.#.#"
    validations:
        required: true
-
    type: "input"
    attributes:
        label: "Laravel version"
        placeholder: "#.#.#"
    validations:
        required: false
-
    type: "input"
    attributes:
        label: "PHP version"
        placeholder: "#.#.#"
    validations:
        required: false
-
    type: "input"
    attributes:
        label: "Database engine & version"
        placeholder: "#.#"
    validations:
        required: false
-
    type: "markdown"
    attributes:
        value: "Description"
    validations:
        required: true
-
    type: "markdown"
    attributes:
        value: "Steps To Reproduce"
    validations:
        required: true
